export const ACHIEVEMENT_CATEGORIES = Object.freeze([
  Object.freeze({
    id: "all",
    label: "全部",
    icon: "✦",
    caption: "收录旅途中所有值得铭记的时刻",
  }),
  Object.freeze({
    id: "fate",
    label: "命运",
    icon: "◎",
    caption: "命运桌、自动结算与角色成长",
  }),
  Object.freeze({
    id: "expedition",
    label: "远征",
    icon: "⚔",
    caption: "探索深度、战斗经历与成功撤离",
  }),
  Object.freeze({
    id: "companion",
    label: "伙伴",
    icon: "♥",
    caption: "宠物收集、编队与羁绊见证",
  }),
  Object.freeze({
    id: "territory",
    label: "领地",
    icon: "▦",
    caption: "基地建设、设施协同与领地升阶",
  }),
]);
const defineAchievement = (definition) => Object.freeze({
  ...definition,
  target: Math.max(1, Math.floor(Number(definition.target) || 1)),
  reward: Object.freeze({ ...(definition.reward || {}) }),
});

/**
 * Long-term milestones only. Every metric is treated as a high-water mark by
 * AchievementSystem, so reaching a milestone can never be undone by spending,
 * changing formation, or demolishing a building before claiming the reward.
 */
export const ACHIEVEMENT_DEFINITIONS = Object.freeze([
  defineAchievement({
    id: "fate_10",
    category: "fate",
    metric: "totalFlips",
    icon: "◎",
    title: "命运初动",
    desc: "累计翻面 10 次",
    target: 10,
    reward: { coins: 80 },
  }),
  defineAchievement({
    id: "fate_100",
    category: "fate",
    metric: "totalFlips",
    icon: "◎",
    title: "命运轮转",
    desc: "累计翻面 100 次",
    target: 100,
    reward: { coins: 300 },
  }),
  defineAchievement({
    id: "fate_500",
    category: "fate",
    metric: "totalFlips",
    icon: "◎",
    title: "命运长河",
    desc: "累计翻面 500 次",
    target: 500,
    reward: { coins: 600 },
  }),
  defineAchievement({
    id: "table_coin_2",
    category: "fate",
    metric: "fateCoins",
    icon: "G",
    title: "桌面扩充",
    desc: "桌面硬币达到 2 枚",
    target: 2,
    reward: { rubies: 10 },
  }),
  defineAchievement({
    id: "table_coin_4",
    category: "fate",
    metric: "fateCoins",
    icon: "G",
    title: "命运阵列",
    desc: "桌面硬币达到 4 枚",
    target: 4,
    reward: { rubies: 25 },
  }),
  defineAchievement({
    id: "assistant_first",
    category: "fate",
    metric: "assistants",
    icon: "⚙",
    title: "第一位助手",
    desc: "招募 1 位自动结算助手",
    target: 1,
    reward: { coins: 120 },
  }),
  defineAchievement({
    id: "hero_level_5",
    category: "fate",
    metric: "playerLevel",
    icon: "Lv",
    title: "训练有素",
    desc: "角色等级达到 Lv.5",
    target: 5,
    reward: { coins: 400 },
  }),
  defineAchievement({
    id: "expedition_depth_3",
    category: "expedition",
    metric: "bestDepth",
    icon: "⚔",
    title: "踏入荒野",
    desc: "单次远征最深到达区域 3",
    target: 3,
    reward: { coins: 200 },
  }),
  defineAchievement({
    id: "expedition_depth_5",
    category: "expedition",
    metric: "bestDepth",
    icon: "⚔",
    title: "深入险境",
    desc: "单次远征最深到达区域 5",
    target: 5,
    reward: { crystals: 35 },
  }),
  defineAchievement({
    id: "expedition_depth_8",
    category: "expedition",
    metric: "bestDepth",
    icon: "◆",
    title: "直面核心",
    desc: "单次远征最深到达区域 8",
    target: 8,
    reward: { crystals: 60 },
  }),
  defineAchievement({
    id: "extraction_1",
    category: "expedition",
    metric: "extractions",
    icon: "↩",
    title: "平安归来",
    desc: "成功撤离 1 次",
    target: 1,
    reward: { coins: 250 },
  }),
  defineAchievement({
    id: "extraction_3",
    category: "expedition",
    metric: "extractions",
    icon: "↩",
    title: "可靠的归途",
    desc: "成功撤离 3 次",
    target: 3,
    reward: { rubies: 40 },
  }),
  defineAchievement({
    id: "extraction_10",
    category: "expedition",
    metric: "extractions",
    icon: "↩",
    title: "远征老手",
    desc: "成功撤离 10 次",
    target: 10,
    reward: { rubies: 100 },
  }),
  defineAchievement({
    id: "pet_first",
    category: "companion",
    metric: "unlockedPets",
    icon: "P",
    title: "第一位伙伴",
    desc: "解锁 1 只宠物",
    target: 1,
    reward: { coins: 120 },
  }),
  defineAchievement({
    id: "pet_collection_3",
    category: "companion",
    metric: "unlockedPets",
    icon: "P",
    title: "伙伴集结",
    desc: "解锁 3 只宠物",
    target: 3,
    reward: { coins: 300 },
  }),
  defineAchievement({
    id: "pet_team",
    category: "companion",
    metric: "equippedPets",
    icon: "P",
    title: "完整小队",
    desc: "曾同时上阵 3 只宠物",
    target: 3,
    reward: { rubies: 30 },
  }),
  defineAchievement({
    id: "pet_friendship_40",
    category: "companion",
    metric: "maxPetFriendship",
    icon: "♥",
    title: "默契萌芽",
    desc: "任意宠物羁绊达到 40",
    target: 40,
    reward: { crystals: 30 },
  }),
  defineAchievement({
    id: "pet_friendship_80",
    category: "companion",
    metric: "maxPetFriendship",
    icon: "♥",
    title: "挚友同行",
    desc: "任意宠物羁绊达到 80",
    target: 80,
    reward: { rubies: 50 },
  }),
  defineAchievement({
    id: "territory_first",
    category: "territory",
    metric: "territoryRank",
    icon: "T",
    title: "落脚之地",
    desc: "修复主基地并达到领地 R1",
    target: 1,
    reward: { crystals: 30 },
  }),
  defineAchievement({
    id: "territory_rank_3",
    category: "territory",
    metric: "territoryRank",
    icon: "T",
    title: "协同聚落",
    desc: "领地达到 R3",
    target: 3,
    reward: { coins: 800 },
  }),
  defineAchievement({
    id: "territory_rank_5",
    category: "territory",
    metric: "territoryRank",
    icon: "T",
    title: "核心领地",
    desc: "领地达到 R5",
    target: 5,
    reward: { rubies: 150 },
  }),
  defineAchievement({
    id: "construction_6",
    category: "territory",
    metric: "constructionScore",
    icon: "▦",
    title: "基地成形",
    desc: "最高建设度达到 6",
    target: 6,
    reward: { crystals: 50 },
  }),
  defineAchievement({
    id: "construction_20",
    category: "territory",
    metric: "constructionScore",
    icon: "▦",
    title: "边境丰碑",
    desc: "最高建设度达到 20",
    target: 20,
    reward: { rubies: 200 },
  }),
]);
